#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
push-artifacts.sh --artifact PATH [--dest DEVICE_PATH] [options]

Push built Android artifacts to the locally USB-connected device.

Options:
  --artifact PATH       Add an artifact to push. Repeatable.
  --dest DEVICE_PATH    Destination for the previous artifact. Optional only when
                        --product-out can infer it from system/product/vendor paths.
  --product-out PATH    Product out path used to infer device destination from partition path.
  --destinations-file FILE
                        Project-local artifact destination memory file.
  --learn-destinations  After successful push, update --destinations-file with artifact rel -> device path mappings.
  --reboot             Reboot after push.
  --wait-boot          Wait for boot completion after reboot.
  --dry-run            Print intended push operations only.

Environment:
  ADB                  adb command. Can be adb, adb.exe, or /mnt/c/.../adb.exe.

Examples:
  ADB=/mnt/c/Android/platform-tools/adb.exe push-artifacts.sh \
    --artifact /mnt/repo/out/target/product/foo/system/framework/services.jar --reboot
USAGE
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

ADB="${ADB:-adb}"
PRODUCT_OUT=""
DESTINATIONS_FILE=""
LEARN_DESTINATIONS=false
REBOOT=false
WAIT_BOOT=false
DRY_RUN=false
ARTIFACTS=()
DESTS=()

last_artifact_index() {
  echo "$((${#ARTIFACTS[@]} - 1))"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --artifact)
      ARTIFACTS+=("${2:-}")
      DESTS+=("")
      shift 2
      ;;
    --dest)
      [[ ${#ARTIFACTS[@]} -gt 0 ]] || die "--dest must follow --artifact"
      DESTS[$(last_artifact_index)]="${2:-}"
      shift 2
      ;;
    --product-out) PRODUCT_OUT="${2:-}"; shift 2 ;;
    --destinations-file) DESTINATIONS_FILE="${2:-}"; shift 2 ;;
    --learn-destinations) LEARN_DESTINATIONS=true; shift ;;
    --reboot) REBOOT=true; shift ;;
    --wait-boot) WAIT_BOOT=true; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

[[ ${#ARTIFACTS[@]} -gt 0 ]] || die "At least one --artifact is required"

declare -A CODEX_ARTIFACT_DESTINATIONS=()
if [[ -n "$DESTINATIONS_FILE" && -f "$DESTINATIONS_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$DESTINATIONS_FILE"
fi

adb_cmd_path() {
  command -v "$ADB" 2>/dev/null || true
}

is_windows_adb() {
  local resolved
  resolved="$(adb_cmd_path)"
  [[ "$ADB" == *.exe || "$resolved" == *.exe ]]
}

path_for_adb() {
  local path="$1"
  if is_windows_adb && command -v wslpath >/dev/null 2>&1; then
    wslpath -w "$path"
  else
    printf "%s" "$path"
  fi
}

infer_dest() {
  local artifact="$1"
  local rel

  if [[ -n "$PRODUCT_OUT" ]]; then
    PRODUCT_OUT="${PRODUCT_OUT%/}"
    if [[ "$artifact" == "$PRODUCT_OUT/"* ]]; then
      rel="${artifact#"$PRODUCT_OUT"/}"
      if [[ -n "${CODEX_ARTIFACT_DESTINATIONS[$rel]+set}" ]]; then
        printf "%s" "${CODEX_ARTIFACT_DESTINATIONS[$rel]}"
        return 0
      fi
      case "$rel" in
        system/*|system_ext/*|product/*|vendor/*|odm/*)
          printf "/%s" "$rel"
          return 0
          ;;
      esac
    fi
  fi

  return 1
}

artifact_rel() {
  local artifact="$1"
  if [[ -n "$PRODUCT_OUT" ]]; then
    PRODUCT_OUT="${PRODUCT_OUT%/}"
    if [[ "$artifact" == "$PRODUCT_OUT/"* ]]; then
      printf "%s" "${artifact#"$PRODUCT_OUT"/}"
      return 0
    fi
  fi
  return 1
}

write_destinations_file() {
  [[ -n "$DESTINATIONS_FILE" ]] || return 0
  mkdir -p "$(dirname "$DESTINATIONS_FILE")"
  local tmp key
  tmp="$(mktemp)"
  {
    echo "#!/usr/bin/env bash"
    echo "# Project-local artifact destination memory. Generated by push-artifacts.sh."
    echo "declare -A CODEX_ARTIFACT_DESTINATIONS=()"
    while IFS= read -r key; do
      [[ -n "$key" ]] || continue
      printf "CODEX_ARTIFACT_DESTINATIONS[%q]=%q\n" "$key" "${CODEX_ARTIFACT_DESTINATIONS[$key]}"
    done < <(printf "%s\n" "${!CODEX_ARTIFACT_DESTINATIONS[@]}" | sort)
  } >"$tmp"
  mv "$tmp" "$DESTINATIONS_FILE"
  chmod +x "$DESTINATIONS_FILE"
}

learn_destination() {
  local artifact="$1"
  local dest="$2"
  local rel
  [[ "$LEARN_DESTINATIONS" == true ]] || return 0
  [[ -n "$DESTINATIONS_FILE" ]] || die "--learn-destinations requires --destinations-file"
  rel="$(artifact_rel "$artifact" || true)"
  [[ -n "$rel" ]] || return 0
  CODEX_ARTIFACT_DESTINATIONS[$rel]="$dest"
  write_destinations_file
  echo "DESTINATION_MEMORY artifact_rel=$rel dest=$dest file=$DESTINATIONS_FILE"
}

run_adb() {
  if [[ "$DRY_RUN" == true ]]; then
    printf "ADB"
    printf " %q" "$@"
    printf "\n"
  else
    "$ADB" "$@"
  fi
}

command -v "$ADB" >/dev/null 2>&1 || [[ -x "$ADB" ]] || die "adb not found. Set ADB=/path/to/adb or adb.exe."

PUSH_PAIRS=()
for i in "${!ARTIFACTS[@]}"; do
  artifact="${ARTIFACTS[$i]}"
  [[ -f "$artifact" ]] || die "artifact not found: $artifact"
  dest="${DESTS[$i]}"
  if [[ -z "$dest" ]]; then
    dest="$(infer_dest "$artifact" || true)"
  fi
  [[ -n "$dest" ]] || die "Cannot infer destination for $artifact; provide --dest"
  PUSH_PAIRS+=("$artifact|$dest")
done

if [[ "$DRY_RUN" == false ]]; then
  run_adb wait-for-device >/dev/null
fi
run_adb root >/dev/null || true
run_adb remount >/dev/null

for pair in "${PUSH_PAIRS[@]}"; do
  artifact="${pair%%|*}"
  dest="${pair#*|}"
  host_path="$(path_for_adb "$artifact")"
  echo "PUSH $artifact -> $dest"
  run_adb push "$host_path" "$dest" >/dev/null
  if [[ "$DRY_RUN" == false ]]; then
    learn_destination "$artifact" "$dest"
  fi
done

run_adb shell sync >/dev/null || true

if [[ "$REBOOT" == true ]]; then
  run_adb reboot
  if [[ "$WAIT_BOOT" == true ]]; then
    run_adb wait-for-device
    if [[ "$DRY_RUN" == false ]]; then
      until [[ "$("$ADB" shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" == "1" ]]; do
        sleep 1
      done
    fi
    echo "BOOT_OK"
  fi
fi

echo "PUSH_OK count=${#PUSH_PAIRS[@]}"
