#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
PLUGIN_ROOT = SCRIPT_PATH.parents[1]
REPO_ROOT = PLUGIN_ROOT.parents[1]
RULES_SOURCE = PLUGIN_ROOT / "lib" / "android_framework_ops" / "knowledge_rules.py"
PLUGIN_MANIFEST = PLUGIN_ROOT / ".codex-plugin" / "plugin.json"
OUTPUT_BASENAME = "akbs_validation_rules.py"


def read_plugin_version() -> str:
    payload = json.loads(PLUGIN_MANIFEST.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"Invalid plugin manifest: {PLUGIN_MANIFEST}")
    version = str(payload.get("version") or "").strip()
    if not version:
        raise SystemExit(f"Missing plugin version in {PLUGIN_MANIFEST}")
    return version


def read_rules_contract_version(source: str) -> str:
    match = re.search(r'^AKBS_RULES_CONTRACT_VERSION\s*=\s*["\']([^"\']+)["\']', source, re.M)
    if not match:
        raise SystemExit("Missing AKBS_RULES_CONTRACT_VERSION in knowledge_rules.py")
    return match.group(1)


def default_source_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            text=True,
            capture_output=True,
            check=True,
        )
    except Exception:
        return "unknown"
    return result.stdout.strip() or "unknown"


def output_path(args: argparse.Namespace) -> Path:
    if args.output_file and args.output_dir:
        raise SystemExit("Use only one of --output-file or --output-dir")
    if args.output_file:
        return Path(args.output_file).expanduser().resolve()
    if args.output_dir:
        return Path(args.output_dir).expanduser().resolve() / OUTPUT_BASENAME
    return Path.cwd() / OUTPUT_BASENAME


def generated_header(*, plugin_version: str, contract_version: str, source_commit: str) -> str:
    return (
        "# GENERATED FROM android_framework_ops.knowledge_rules\n"
        f"# Plugin: android-framework-ops {plugin_version}\n"
        f"# AKBS_RULES_CONTRACT_VERSION: {contract_version}\n"
        f"# Source commit: {source_commit}\n"
        "# Do not edit this file by hand. Regenerate it from the plugin repository.\n"
        "\n"
    )


def export_rules(destination: Path, *, source_commit: str) -> Path:
    source = RULES_SOURCE.read_text(encoding="utf-8")
    plugin_version = read_plugin_version()
    contract_version = read_rules_contract_version(source)
    header = generated_header(
        plugin_version=plugin_version,
        contract_version=contract_version,
        source_commit=source_commit,
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(header + source, encoding="utf-8")
    return destination


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export android-framework-ops deterministic rules as a self-contained akbs_validation_rules.py file."
    )
    parser.add_argument("--output-dir", help="Directory that will receive akbs_validation_rules.py.")
    parser.add_argument("--output-file", help="Exact generated file path. Mutually exclusive with --output-dir.")
    parser.add_argument("--source-commit", default="", help="Source commit to embed in the generated header.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(list(argv or sys.argv[1:]))
    commit = str(args.source_commit or "").strip() or default_source_commit()
    destination = export_rules(output_path(args), source_commit=commit)
    print(destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
