#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
generate-build-push.sh --repo PATH --discovery-file FILE [options]

Generate repo-local .codex/build-push.config.sh and .codex/build-push.sh.
The generated scripts contain project build settings only; no passwords.

Required:
  --repo PATH              Locally mounted Android source path.

Input options:
  --discovery-file FILE    File generated by discover-project.sh.
  --ssh-host HOST          SSH host if no discovery file is used.
  --remote-root PATH       Remote repo path if no discovery file is used.
  --envsetup PATH          Envsetup path. Default: build/envsetup.sh.
  --lunch TARGET           Lunch target.
  --product-out REL        Product out relative path, e.g. out/target/product/foo.

Optional:
  --dry-run                Print target paths only.
  --profile NAME           Add or update a project-local build profile.
  --modules LIST           Space-separated module list for --profile.
  --artifacts LIST         Space-separated artifact names for --profile.
  --only-profile           Only update .codex/build-push.profiles.sh.

Existing config/script files are backed up as *.bak.<timestamp> before replacement.
Project custom profiles live in .codex/build-push.profiles.sh and are preserved.
USAGE
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

single_quote() {
  printf "'%s'" "$(printf "%s" "$1" | sed "s/'/'\\\\''/g")"
}

backup_and_write() {
  local target="$1"
  local tmp="$2"
  if [[ -f "$target" ]]; then
    if cmp -s "$target" "$tmp"; then
      rm -f "$tmp"
      echo "UNCHANGED $target"
      return
    fi
    cp -p "$target" "$target.bak.$(date +%Y%m%d-%H%M%S)"
  fi
  mv "$tmp" "$target"
  echo "WROTE $target"
}

REPO=""
DISCOVERY_FILE=""
SSH_HOST=""
REMOTE_ROOT=""
ENVSETUP_SCRIPT="build/envsetup.sh"
LUNCH_TARGET=""
PRODUCT_OUT_DIR_REL=""
DRY_RUN=false
PROFILE_TO_SET=""
PROFILE_MODULES=""
PROFILE_ARTIFACTS=""
ONLY_PROFILE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="${2:-}"; shift 2 ;;
    --discovery-file) DISCOVERY_FILE="${2:-}"; shift 2 ;;
    --ssh-host) SSH_HOST="${2:-}"; shift 2 ;;
    --remote-root) REMOTE_ROOT="${2:-}"; shift 2 ;;
    --envsetup) ENVSETUP_SCRIPT="${2:-}"; shift 2 ;;
    --lunch) LUNCH_TARGET="${2:-}"; shift 2 ;;
    --product-out) PRODUCT_OUT_DIR_REL="${2:-}"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --profile) PROFILE_TO_SET="${2:-}"; shift 2 ;;
    --modules) PROFILE_MODULES="${2:-}"; shift 2 ;;
    --artifacts) PROFILE_ARTIFACTS="${2:-}"; shift 2 ;;
    --only-profile) ONLY_PROFILE=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

[[ -n "$REPO" ]] || die "--repo is required"
[[ -d "$REPO" ]] || die "repo path does not exist: $REPO"

if [[ -n "$DISCOVERY_FILE" ]]; then
  [[ -f "$DISCOVERY_FILE" ]] || die "discovery file not found: $DISCOVERY_FILE"
  # shellcheck disable=SC1090
  source "$DISCOVERY_FILE"
fi

SSH_HOST="${SSH_HOST:-}"
REMOTE_ROOT="${REMOTE_ROOT:-}"
ENVSETUP_SCRIPT="${ENVSETUP_SCRIPT:-build/envsetup.sh}"
LUNCH_TARGET="${LUNCH_TARGET:-}"
PRODUCT_OUT_DIR_REL="${PRODUCT_OUT_DIR_REL:-}"

CODEX_DIR="$REPO/.codex"
CONFIG_PATH="$CODEX_DIR/build-push.config.sh"
SCRIPT_PATH="$CODEX_DIR/build-push.sh"
SESSION_SCRIPT_PATH="$CODEX_DIR/build-session.sh"
PROFILES_PATH="$CODEX_DIR/build-push.profiles.sh"

write_or_update_profile() {
  local profile="$1"
  local modules="$2"
  local artifacts="$3"
  [[ -n "$profile" ]] || return 0
  [[ -n "$modules" ]] || die "--modules is required when --profile is used"

  mkdir -p "$CODEX_DIR"
  if [[ ! -f "$PROFILES_PATH" ]]; then
    cat >"$PROFILES_PATH" <<'EOF_PROFILES'
#!/usr/bin/env bash
# Project-specific build profiles. This file is preserved by the generator.
# Add new modules here after Codex infers them from the current requirement,
# changed files, Android.bp/Android.mk, existing build scripts, or build output.
EOF_PROFILES
    chmod +x "$PROFILES_PATH"
  fi

  local begin="# BEGIN codex-profile: $profile"
  local end="# END codex-profile: $profile"
  local tmp
  tmp="$(mktemp)"
  awk -v begin="$begin" -v end="$end" '
    $0 == begin {skip=1; next}
    $0 == end {skip=0; next}
    !skip {print}
  ' "$PROFILES_PATH" >"$tmp"
  {
    printf "\n%s\n" "$begin"
    printf "BUILD_PROFILE_MODULES[%s]=%s\n" "$(single_quote "$profile")" "$(single_quote "$modules")"
    if [[ -n "$artifacts" ]]; then
      printf "BUILD_PROFILE_ARTIFACTS[%s]=%s\n" "$(single_quote "$profile")" "$(single_quote "$artifacts")"
    fi
    printf "%s\n" "$end"
  } >>"$tmp"
  backup_and_write "$PROFILES_PATH" "$tmp"
  chmod +x "$PROFILES_PATH"
}

if [[ "$DRY_RUN" == true ]]; then
  if [[ "$ONLY_PROFILE" == false ]]; then
    echo "WOULD_WRITE $CONFIG_PATH"
    echo "WOULD_WRITE $SCRIPT_PATH"
    echo "WOULD_WRITE $SESSION_SCRIPT_PATH"
  fi
  echo "WOULD_PRESERVE_OR_CREATE $PROFILES_PATH"
  exit 0
fi

mkdir -p "$CODEX_DIR"

if [[ "$ONLY_PROFILE" == true ]]; then
  write_or_update_profile "$PROFILE_TO_SET" "$PROFILE_MODULES" "$PROFILE_ARTIFACTS"
  exit 0
fi

[[ -n "$SSH_HOST" ]] || die "SSH_HOST is missing"
[[ -n "$REMOTE_ROOT" ]] || die "REMOTE_ROOT is missing"
[[ -n "$LUNCH_TARGET" ]] || die "LUNCH_TARGET is missing"
[[ -n "$PRODUCT_OUT_DIR_REL" ]] || die "PRODUCT_OUT_DIR_REL is missing"

CONFIG_TMP="$(mktemp)"
cat >"$CONFIG_TMP" <<EOF_CONFIG
#!/usr/bin/env bash
# Project-local Android remote build config. No secrets.

SSH_HOST=$(single_quote "$SSH_HOST")
REMOTE_ROOT=$(single_quote "$REMOTE_ROOT")
ENVSETUP_SCRIPT=$(single_quote "$ENVSETUP_SCRIPT")
LUNCH_TARGET=$(single_quote "$LUNCH_TARGET")
PRODUCT_OUT_DIR_REL=$(single_quote "$PRODUCT_OUT_DIR_REL")
BUILD_PUSH_LOG_REL='.codex/logs'
EOF_CONFIG

SCRIPT_TMP="$(mktemp)"
cat >"$SCRIPT_TMP" <<'EOF_SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/build-push.config.sh"

usage() {
  cat <<'USAGE'
build-push.sh plan|build|profiles [options]

Profiles are project-local and loaded from .codex/build-push.profiles.sh.

Options:
  --profile NAME      Project-local profile name.
  --modules LIST      Direct module list for one-off builds.
  --artifacts LIST    Direct artifact name list for one-off artifact discovery.
  --stream-log       Stream build output while also saving the log.
  --verbose          Enable shell tracing.
  -j N               Build jobs. Default: nproc.

Default behavior is quiet: full build output is saved under .codex/logs.
USAGE
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

ACTION="${1:-}"
[[ -n "$ACTION" ]] || { usage; exit 1; }
shift || true

PROFILE=""
DIRECT_MODULES=""
DIRECT_ARTIFACTS=""
STREAM_LOG=false
VERBOSE=false
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 8)}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) PROFILE="${2:-}"; shift 2 ;;
    --modules) DIRECT_MODULES="${2:-}"; shift 2 ;;
    --artifacts) DIRECT_ARTIFACTS="${2:-}"; shift 2 ;;
    --stream-log) STREAM_LOG=true; shift ;;
    --verbose) VERBOSE=true; shift ;;
    -j) JOBS="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

[[ "$VERBOSE" == true ]] && set -x

PRODUCT_OUT="$REMOTE_ROOT/$PRODUCT_OUT_DIR_REL"
LOG_DIR="$REMOTE_ROOT/${BUILD_PUSH_LOG_REL:-.codex/logs}"
MEMORY_FILE="$SCRIPT_DIR/build-push.memory.sh"

declare -A BUILD_PROFILE_MODULES=()
declare -A BUILD_PROFILE_ARTIFACTS=()
declare -A BUILD_PROFILE_LAST_SUCCESS_AT=()
declare -A BUILD_PROFILE_LAST_MODULES=()
declare -A BUILD_PROFILE_LAST_ARTIFACTS=()
declare -A BUILD_PROFILE_LAST_PRODUCT_OUT_REL=()
declare -A BUILD_PROFILE_LAST_LUNCH=()
BUILD_PROFILE_MODULES[services]="services"
BUILD_PROFILE_ARTIFACTS[services]="services.jar"
BUILD_PROFILE_MODULES[framework]="framework-minus-apex"
BUILD_PROFILE_ARTIFACTS[framework]="framework.jar"
BUILD_PROFILE_MODULES[framework-res]="framework-res"
BUILD_PROFILE_ARTIFACTS[framework-res]="framework-res.apk"
CUSTOM_PROFILES_FILE="$SCRIPT_DIR/build-push.profiles.sh"
if [[ -f "$CUSTOM_PROFILES_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CUSTOM_PROFILES_FILE"
fi
if [[ -f "$MEMORY_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$MEMORY_FILE"
fi

profile_modules() {
  if [[ -n "$DIRECT_MODULES" ]]; then
    echo "$DIRECT_MODULES"
    return
  fi
  [[ -n "$1" ]] || die "--profile or --modules is required"
  if [[ -n "${BUILD_PROFILE_MODULES[$1]+set}" ]]; then
    echo "${BUILD_PROFILE_MODULES[$1]}"
    return
  fi
  die "Unknown profile: $1. Add it to .codex/build-push.profiles.sh first."
}

profile_artifact_names() {
  if [[ -n "$DIRECT_ARTIFACTS" ]]; then
    echo "$DIRECT_ARTIFACTS"
    return
  fi
  [[ -n "$1" ]] || return 0
  if [[ -n "${BUILD_PROFILE_ARTIFACTS[$1]+set}" ]]; then
    echo "${BUILD_PROFILE_ARTIFACTS[$1]}"
    return
  fi
  echo ""
}

list_profiles() {
  if [[ ${#BUILD_PROFILE_MODULES[@]} -eq 0 ]]; then
    echo "PROFILE none"
    return
  fi
  local key
  for key in "${!BUILD_PROFILE_MODULES[@]}"; do
    printf "PROFILE %s modules=%s artifacts=%s last_success=%s\n" \
      "$key" "${BUILD_PROFILE_MODULES[$key]}" "${BUILD_PROFILE_ARTIFACTS[$key]:-}" "${BUILD_PROFILE_LAST_SUCCESS_AT[$key]:-}"
  done | sort
}

write_assoc_assignment() {
  local array_name="$1"
  local key
  local -a keys=()
  while IFS= read -r key; do
    [[ -n "$key" ]] && keys+=("$key")
  done < <(eval "printf '%s\n' \"\${!${array_name}[@]}\"" | sort)
  printf "declare -A %s=()\n" "$array_name"
  for key in "${keys[@]}"; do
    local value
    value="$(eval "printf '%s' \"\${${array_name}[\$key]}\"")"
    printf "%s[%q]=%q\n" "$array_name" "$key" "$value"
  done
}

record_profile_success() {
  local profile_key="$1"
  local modules="$2"
  local artifacts="$3"
  [[ -n "$profile_key" ]] || profile_key="direct"
  BUILD_PROFILE_LAST_SUCCESS_AT[$profile_key]="$(date '+%F %T %z')"
  BUILD_PROFILE_LAST_MODULES[$profile_key]="$modules"
  BUILD_PROFILE_LAST_ARTIFACTS[$profile_key]="$artifacts"
  BUILD_PROFILE_LAST_PRODUCT_OUT_REL[$profile_key]="$PRODUCT_OUT_DIR_REL"
  BUILD_PROFILE_LAST_LUNCH[$profile_key]="$LUNCH_TARGET"

  local tmp
  tmp="$(mktemp)"
  {
    echo "#!/usr/bin/env bash"
    echo "# Project-local successful build memory. Generated by .codex/build-push.sh."
    write_assoc_assignment BUILD_PROFILE_LAST_SUCCESS_AT
    write_assoc_assignment BUILD_PROFILE_LAST_MODULES
    write_assoc_assignment BUILD_PROFILE_LAST_ARTIFACTS
    write_assoc_assignment BUILD_PROFILE_LAST_PRODUCT_OUT_REL
    write_assoc_assignment BUILD_PROFILE_LAST_LUNCH
  } >"$tmp"
  mv "$tmp" "$MEMORY_FILE"
  chmod +x "$MEMORY_FILE"
  echo "PROFILE_MEMORY profile=$profile_key file=$MEMORY_FILE"
}

print_key_errors() {
  local log_file="$1"
  [[ -f "$log_file" ]] || return 0

  echo "KEY_ERRORS_BEGIN"
  grep -n -i -E \
    '(^|[^A-Za-z])(error:|fatal:|FAILED:|ninja failed|build failed|soong bootstrap failed|ckati failed|undefined reference|No rule to make target|module .* missing|Traceback \(most recent call last\)|Exception:|FAILED\(.*\))' \
    "$log_file" 2>/dev/null |
    grep -v -i -E 'warning:|deprecated|note:' |
    tail -n 40 || true
  echo "KEY_ERRORS_END"
}

print_artifacts() {
  local found=false
  local name
  local artifact_names
  local rel
  artifact_names="$(profile_artifact_names "$PROFILE")"
  if [[ -z "$artifact_names" ]]; then
    echo "ARTIFACT none_declared"
    return
  fi
  echo "PRODUCT_OUT_REL $PRODUCT_OUT_DIR_REL"
  for name in $artifact_names; do
    while IFS= read -r artifact; do
      [[ -n "$artifact" ]] || continue
      found=true
      printf "ARTIFACT %s\n" "$artifact"
      if [[ "$artifact" == "$PRODUCT_OUT/"* ]]; then
        rel="${artifact#"$PRODUCT_OUT"/}"
        printf "ARTIFACT_REL %s\n" "$rel"
      fi
    done < <(find "$PRODUCT_OUT" -type f -name "$name" 2>/dev/null | sort)
  done
  [[ "$found" == true ]] || echo "ARTIFACT none_found_yet"
}

case "$ACTION" in
  profiles)
    list_profiles
    ;;
  plan)
    MODULES="$(profile_modules "$PROFILE")"
    echo "PLAN profile=$PROFILE"
    echo "REMOTE_ROOT=$REMOTE_ROOT"
    echo "LUNCH_TARGET=$LUNCH_TARGET"
    echo "PRODUCT_OUT=$PRODUCT_OUT"
    echo "PRODUCT_OUT_REL=$PRODUCT_OUT_DIR_REL"
    echo "MODULES=$MODULES"
    print_artifacts
    ;;
  build)
    MODULES="$(profile_modules "$PROFILE")"
    mkdir -p "$LOG_DIR"
    LOG_NAME="${PROFILE:-direct}"
    LOG_FILE="$LOG_DIR/build-${LOG_NAME}-$(date +%Y%m%d-%H%M%S).log"
    echo "BUILD_START profile=$PROFILE log=$LOG_FILE"
    build_rc=0
    if [[ "$STREAM_LOG" == true ]]; then
      set +e
      (
        cd "$REMOTE_ROOT"
        set +u
        # shellcheck disable=SC1090
        source "$ENVSETUP_SCRIPT"
        lunch "$LUNCH_TARGET"
        m -j"$JOBS" $MODULES
      ) 2>&1 | tee "$LOG_FILE"
      build_rc=${PIPESTATUS[0]}
      set -e
    else
      set +e
      (
        cd "$REMOTE_ROOT"
        set +u
        # shellcheck disable=SC1090
        source "$ENVSETUP_SCRIPT"
        lunch "$LUNCH_TARGET"
        m -j"$JOBS" $MODULES
      ) >"$LOG_FILE" 2>&1
      build_rc=$?
      set -e
    fi
    if [[ "$build_rc" -ne 0 ]]; then
      echo "BUILD_FAIL rc=$build_rc profile=$PROFILE log=$LOG_FILE"
      print_key_errors "$LOG_FILE"
      exit "$build_rc"
    fi
    echo "BUILD_OK profile=$PROFILE log=$LOG_FILE"
    record_profile_success "$PROFILE" "$MODULES" "$(profile_artifact_names "$PROFILE")"
    print_artifacts
    ;;
  *)
    usage
    exit 1
    ;;
esac
EOF_SCRIPT

SESSION_TMP="$(mktemp)"
cat >"$SESSION_TMP" <<'EOF_SESSION'
#!/usr/bin/env bash
# Source this file inside a persistent remote shell or tmux session:
#   source .codex/build-session.sh
#   codex_session_init
#   codex_session_build --profile services

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "ERROR: source this file inside a persistent shell; do not execute it directly." >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/build-push.config.sh"

PRODUCT_OUT="$REMOTE_ROOT/$PRODUCT_OUT_DIR_REL"
LOG_DIR="$REMOTE_ROOT/${BUILD_PUSH_LOG_REL:-.codex/logs}"
MEMORY_FILE="$SCRIPT_DIR/build-push.memory.sh"

declare -A BUILD_PROFILE_MODULES=()
declare -A BUILD_PROFILE_ARTIFACTS=()
declare -A BUILD_PROFILE_LAST_SUCCESS_AT=()
declare -A BUILD_PROFILE_LAST_MODULES=()
declare -A BUILD_PROFILE_LAST_ARTIFACTS=()
declare -A BUILD_PROFILE_LAST_PRODUCT_OUT_REL=()
declare -A BUILD_PROFILE_LAST_LUNCH=()
BUILD_PROFILE_MODULES[services]="services"
BUILD_PROFILE_ARTIFACTS[services]="services.jar"
BUILD_PROFILE_MODULES[framework]="framework-minus-apex"
BUILD_PROFILE_ARTIFACTS[framework]="framework.jar"
BUILD_PROFILE_MODULES[framework-res]="framework-res"
BUILD_PROFILE_ARTIFACTS[framework-res]="framework-res.apk"

CUSTOM_PROFILES_FILE="$SCRIPT_DIR/build-push.profiles.sh"
if [[ -f "$CUSTOM_PROFILES_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CUSTOM_PROFILES_FILE"
fi
if [[ -f "$MEMORY_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$MEMORY_FILE"
fi

CODEX_SESSION_BUILD_INITIALIZED="${CODEX_SESSION_BUILD_INITIALIZED:-false}"

codex_session_init() {
  cd "$REMOTE_ROOT" || return 2
  local old_opts="$-"
  set +u
  # shellcheck disable=SC1090
  source "$ENVSETUP_SCRIPT"
  lunch "$LUNCH_TARGET"
  case "$old_opts" in
    *u*) set -u ;;
    *) set +u ;;
  esac
  PRODUCT_OUT="$REMOTE_ROOT/$PRODUCT_OUT_DIR_REL"
  export PRODUCT_OUT
  CODEX_SESSION_BUILD_INITIALIZED=true
  echo "SESSION_BUILD_ENV_OK remote=$REMOTE_ROOT lunch=$LUNCH_TARGET product_out=$PRODUCT_OUT"
}

codex_session_profile_modules() {
  local profile="$1"
  local direct_modules="${2:-}"
  if [[ -n "$direct_modules" ]]; then
    echo "$direct_modules"
    return
  fi
  [[ -n "$profile" ]] || { echo "ERROR: --profile or --modules is required" >&2; return 2; }
  if [[ -n "${BUILD_PROFILE_MODULES[$profile]+set}" ]]; then
    echo "${BUILD_PROFILE_MODULES[$profile]}"
    return
  fi
  echo "ERROR: Unknown profile: $profile. Add it to .codex/build-push.profiles.sh first." >&2
  return 2
}

codex_session_profile_artifact_names() {
  local profile="$1"
  local direct_artifacts="${2:-}"
  if [[ -n "$direct_artifacts" ]]; then
    echo "$direct_artifacts"
    return
  fi
  [[ -n "$profile" ]] || return 0
  if [[ -n "${BUILD_PROFILE_ARTIFACTS[$profile]+set}" ]]; then
    echo "${BUILD_PROFILE_ARTIFACTS[$profile]}"
    return
  fi
  echo ""
}

codex_session_write_assoc_assignment() {
  local array_name="$1"
  local key
  local -a keys=()
  while IFS= read -r key; do
    [[ -n "$key" ]] && keys+=("$key")
  done < <(eval "printf '%s\n' \"\${!${array_name}[@]}\"" | sort)
  printf "declare -A %s=()\n" "$array_name"
  for key in "${keys[@]}"; do
    local value
    value="$(eval "printf '%s' \"\${${array_name}[\$key]}\"")"
    printf "%s[%q]=%q\n" "$array_name" "$key" "$value"
  done
}

codex_session_record_profile_success() {
  local profile_key="$1"
  local modules="$2"
  local artifacts="$3"
  [[ -n "$profile_key" ]] || profile_key="direct"
  BUILD_PROFILE_LAST_SUCCESS_AT[$profile_key]="$(date '+%F %T %z')"
  BUILD_PROFILE_LAST_MODULES[$profile_key]="$modules"
  BUILD_PROFILE_LAST_ARTIFACTS[$profile_key]="$artifacts"
  BUILD_PROFILE_LAST_PRODUCT_OUT_REL[$profile_key]="$PRODUCT_OUT_DIR_REL"
  BUILD_PROFILE_LAST_LUNCH[$profile_key]="$LUNCH_TARGET"

  local tmp
  tmp="$(mktemp)"
  {
    echo "#!/usr/bin/env bash"
    echo "# Project-local successful build memory. Generated by .codex/build-session.sh."
    codex_session_write_assoc_assignment BUILD_PROFILE_LAST_SUCCESS_AT
    codex_session_write_assoc_assignment BUILD_PROFILE_LAST_MODULES
    codex_session_write_assoc_assignment BUILD_PROFILE_LAST_ARTIFACTS
    codex_session_write_assoc_assignment BUILD_PROFILE_LAST_PRODUCT_OUT_REL
    codex_session_write_assoc_assignment BUILD_PROFILE_LAST_LUNCH
  } >"$tmp"
  mv "$tmp" "$MEMORY_FILE"
  chmod +x "$MEMORY_FILE"
  echo "PROFILE_MEMORY profile=$profile_key file=$MEMORY_FILE"
}

codex_session_print_key_errors() {
  local log_file="$1"
  [[ -f "$log_file" ]] || return 0
  echo "KEY_ERRORS_BEGIN"
  grep -n -i -E \
    '(^|[^A-Za-z])(error:|fatal:|FAILED:|ninja failed|build failed|soong bootstrap failed|ckati failed|undefined reference|No rule to make target|module .* missing|Traceback \(most recent call last\)|Exception:|FAILED\(.*\))' \
    "$log_file" 2>/dev/null |
    grep -v -i -E 'warning:|deprecated|note:' |
    tail -n 40 || true
  echo "KEY_ERRORS_END"
}

codex_session_print_artifacts() {
  local profile="$1"
  local direct_artifacts="${2:-}"
  local artifact_names name artifact rel found=false
  artifact_names="$(codex_session_profile_artifact_names "$profile" "$direct_artifacts")"
  if [[ -z "$artifact_names" ]]; then
    echo "ARTIFACT none_declared"
    return
  fi
  echo "PRODUCT_OUT_REL $PRODUCT_OUT_DIR_REL"
  for name in $artifact_names; do
    while IFS= read -r artifact; do
      [[ -n "$artifact" ]] || continue
      found=true
      printf "ARTIFACT %s\n" "$artifact"
      if [[ "$artifact" == "$PRODUCT_OUT/"* ]]; then
        rel="${artifact#"$PRODUCT_OUT"/}"
        printf "ARTIFACT_REL %s\n" "$rel"
      fi
    done < <(find "$PRODUCT_OUT" -type f -name "$name" 2>/dev/null | sort)
  done
  [[ "$found" == true ]] || echo "ARTIFACT none_found_yet"
}

codex_session_plan() {
  local profile="" direct_modules="" direct_artifacts=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --profile) profile="${2:-}"; shift 2 ;;
      --modules) direct_modules="${2:-}"; shift 2 ;;
      --artifacts) direct_artifacts="${2:-}"; shift 2 ;;
      *) echo "ERROR: Unknown argument: $1" >&2; return 2 ;;
    esac
  done
  local modules
  modules="$(codex_session_profile_modules "$profile" "$direct_modules")" || return $?
  echo "PLAN profile=$profile"
  echo "REMOTE_ROOT=$REMOTE_ROOT"
  echo "LUNCH_TARGET=$LUNCH_TARGET"
  echo "PRODUCT_OUT=$PRODUCT_OUT"
  echo "PRODUCT_OUT_REL=$PRODUCT_OUT_DIR_REL"
  echo "MODULES=$modules"
  codex_session_print_artifacts "$profile" "$direct_artifacts"
}

codex_session_build() {
  local profile="" direct_modules="" direct_artifacts="" stream_log=false
  local jobs="${JOBS:-$(nproc 2>/dev/null || echo 8)}"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --profile) profile="${2:-}"; shift 2 ;;
      --modules) direct_modules="${2:-}"; shift 2 ;;
      --artifacts) direct_artifacts="${2:-}"; shift 2 ;;
      --stream-log) stream_log=true; shift ;;
      -j) jobs="${2:-}"; shift 2 ;;
      *) echo "ERROR: Unknown argument: $1" >&2; return 2 ;;
    esac
  done
  if [[ "$CODEX_SESSION_BUILD_INITIALIZED" != true ]]; then
    codex_session_init || return $?
  fi
  local modules log_name log_file build_rc artifact_names
  modules="$(codex_session_profile_modules "$profile" "$direct_modules")" || return $?
  mkdir -p "$LOG_DIR"
  log_name="${profile:-direct}"
  log_file="$LOG_DIR/build-session-${log_name}-$(date +%Y%m%d-%H%M%S).log"
  echo "BUILD_START profile=$profile log=$log_file"
  local old_opts="$-"
  if [[ "$stream_log" == true ]]; then
    set +e
    m -j"$jobs" $modules 2>&1 | tee "$log_file"
    build_rc=${PIPESTATUS[0]}
  else
    set +e
    m -j"$jobs" $modules >"$log_file" 2>&1
    build_rc=$?
  fi
  case "$old_opts" in
    *e*) set -e ;;
    *) set +e ;;
  esac
  if [[ "$build_rc" -ne 0 ]]; then
    echo "BUILD_FAIL rc=$build_rc profile=$profile log=$log_file"
    codex_session_print_key_errors "$log_file"
    return "$build_rc"
  fi
  echo "BUILD_OK profile=$profile log=$log_file"
  artifact_names="$(codex_session_profile_artifact_names "$profile" "$direct_artifacts")"
  codex_session_record_profile_success "$profile" "$modules" "$artifact_names"
  codex_session_print_artifacts "$profile" "$direct_artifacts"
}
EOF_SESSION

chmod +x "$SCRIPT_TMP"
chmod +x "$SESSION_TMP"
backup_and_write "$CONFIG_PATH" "$CONFIG_TMP"
backup_and_write "$SCRIPT_PATH" "$SCRIPT_TMP"
backup_and_write "$SESSION_SCRIPT_PATH" "$SESSION_TMP"
chmod +x "$SCRIPT_PATH"
chmod +x "$SESSION_SCRIPT_PATH"

if [[ ! -f "$PROFILES_PATH" ]]; then
  cat >"$PROFILES_PATH" <<'EOF_PROFILES'
#!/usr/bin/env bash
# Project-specific build profiles. This file is preserved by the generator.
# Add new modules here after Codex infers them from the current requirement,
# changed files, Android.bp/Android.mk, existing build scripts, or build output.
EOF_PROFILES
  chmod +x "$PROFILES_PATH"
  echo "WROTE $PROFILES_PATH"
else
  echo "PRESERVED $PROFILES_PATH"
fi

write_or_update_profile "$PROFILE_TO_SET" "$PROFILE_MODULES" "$PROFILE_ARTIFACTS"
